create table if not exists loan_system(
system_code bigint not null,
loan_id bigint null,
primary_account_num bigint null,
lending_account varchar(255) null,
lending_amount bigint null,
team_center varchar(255) null,
lending_curr varchar(255) null,
remarks varchar(255) null,
desription varchar(255) null,
loan_input_avail char null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint loan_system_pk primary key(system_code));